services:
  mc:
    image: itzg/minecraft-server:stable
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      CF_API_KEY: ${CF_API_KEY}
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.20.1"
      MEMORY: "4096M"
      DIFFICULTY: "2"
      ONLINE_MODE: "false"
      USE_MEOWICE_FLAGS: "true"
      TZ: "Europe/Warsaw"
      CURSEFORGE_FILES: |-
        @/extras/cf-mods.txt
    restart: always
    volumes:
      - "./data:/data"
      - "./mods:/data/mods"
      - "./extras:/extras"
